# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

sentences=["Animals that lay eggs don't have belly buttons",
  "Beavers can hold their breath for 45 minutes under water",
  "Slugs have four noses","Camels have three eyelids",
  "A honey bee can fly at 15mph",
  "A queen bee can lay 800-1,500 eggs per day",
  "A bee has five eyelids",
  "The average speed of a housefly is 4.5 mph",
  "Mosquitoes are attracted to people who just ate bananas",
  "Flamingos turn pink from eating shrimp",
  "Emus and kangaroos cannot walk backward",
  "Cats have over 100 vocal chords",
  "Camel's milk does not curdle",
  "Children tend to grow faster in the spring",
  "Broccoli is the only vegetable that is also a flower",
  "Almonds are part of the peach family",
  "Alaska has the highest percentage of people who walk to work",
  "he San Francisco cable cars are the only mobile national monument",
  "The only food that does not spoil is honey",
  "The Hawaiian alphabet only has 12 letters",
  "A ball of glass will bounce higher than a ball of rubber",
  "Chewing gum while peeling onions will prevent you from crying",
  "If you keep a goldfish in a dark room it will eventually turn white",
  "An ant's sense of smell is stronger than a dog's",
  "Elephants are capable of swimming 20 miles per day",
  "About 11% of the people in the world are left-handed",
  "You blink over 10,000,000 times a year",
  "Americans, on average, eat 18 acres of pizza a day",
  "No word in the English language rhymes with month",
  "You share your birthday with at least 9 million other people in the world",
  "No piece of paper can be folded more than seven times",
  "Oysters can change from one gender to another and back again",
  "The Mona Lisa has no eyebrows",
  "Until the 19th century, solid blocks of tea were used as money in Siberia",
  "When the moon is directly overhead, you weigh slightly less",
  "The oldest known animal was a tortoise, which lived to be 152 years old",
  "Bamboo makes up 99 percent of a panda's diet",
  "Honeybees are the only insects that create a form of food for humans",
  "Pigeons have been trained by the U.S. Coast Guard to spot people lost at sea",
  "Dolphins can jump up to 20 feet in the air","A crocodile cannot move its tongue",
  "Holland is the only country with a national dog",
  "Panama is the only place in the world where you can see the sun rise on the Pacific and set on the Atlantic",
  "Theodore Roosevelt was the only president who was blind in one eye",
  "The most sensitive parts of the body are the mouth and the fingertips",
  "The eye makes movements 50 times every second",
  "Chinese is the most spoken language in the world",
  "The world's biggest pyramid is not in Egypt, but in Mexico",
  "A rainbow can only be seen in the morning or late afternoon"]
